<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class ScholarEnrollmentListsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('scholar_enrollment_lists')->delete();
        
        \DB::table('scholar_enrollment_lists')->insert(array (
            0 => 
            array (
                'id' => 80,
                'code' => 'CE132',
                'subject' => 'Construction Methods & Project Management',
                'unit' => 3,
                'is_lab' => 0,
                'is_nonacademic' => 0,
                'is_failed' => 0,
                'grade' => '1',
                'enrollment_id' => 9,
                'encoded_by' => 1,
                'options' => '[]',
                'created_at' => '2023-06-06 18:10:05',
                'updated_at' => '2023-06-06 18:10:19',
            ),
            1 => 
            array (
                'id' => 81,
                'code' => 'BES132',
                'subject' => 'Technopreneurship',
                'unit' => 3,
                'is_lab' => 0,
                'is_nonacademic' => 0,
                'is_failed' => 0,
                'grade' => '1',
                'enrollment_id' => 9,
                'encoded_by' => 1,
                'options' => '[]',
                'created_at' => '2023-06-06 18:10:05',
                'updated_at' => '2023-06-06 18:10:19',
            ),
            2 => 
            array (
                'id' => 82,
                'code' => 'CE134',
                'subject' => 'Building System Design',
                'unit' => 2,
                'is_lab' => 0,
                'is_nonacademic' => 0,
                'is_failed' => 0,
                'grade' => '1',
                'enrollment_id' => 9,
                'encoded_by' => 1,
                'options' => '[]',
                'created_at' => '2023-06-06 18:10:05',
                'updated_at' => '2023-06-06 18:10:19',
            ),
            3 => 
            array (
                'id' => 83,
                'code' => 'CE134',
                'subject' => 'Building System Design',
                'unit' => 1,
                'is_lab' => 1,
                'is_nonacademic' => 0,
                'is_failed' => 0,
                'grade' => '1',
                'enrollment_id' => 9,
                'encoded_by' => 1,
                'options' => '[]',
                'created_at' => '2023-06-06 18:10:05',
                'updated_at' => '2023-06-06 18:10:19',
            ),
            4 => 
            array (
                'id' => 84,
                'code' => 'CE136',
                'subject' => 'Principles of Transportation Engineering',
                'unit' => 3,
                'is_lab' => 0,
                'is_nonacademic' => 0,
                'is_failed' => 0,
                'grade' => '1',
                'enrollment_id' => 9,
                'encoded_by' => 1,
                'options' => '[]',
                'created_at' => '2023-06-06 18:10:05',
                'updated_at' => '2023-06-06 18:10:19',
            ),
            5 => 
            array (
                'id' => 85,
                'code' => 'CE138',
                'subject' => 'Principles of Reinforced',
                'unit' => 2,
                'is_lab' => 0,
                'is_nonacademic' => 0,
                'is_failed' => 0,
                'grade' => '1',
                'enrollment_id' => 9,
                'encoded_by' => 1,
                'options' => '[]',
                'created_at' => '2023-06-06 18:10:05',
                'updated_at' => '2023-06-06 18:10:19',
            ),
            6 => 
            array (
                'id' => 86,
                'code' => 'CE138',
                'subject' => 'Principles of Reinforced',
                'unit' => 1,
                'is_lab' => 1,
                'is_nonacademic' => 0,
                'is_failed' => 0,
                'grade' => '1',
                'enrollment_id' => 9,
                'encoded_by' => 1,
                'options' => '[]',
                'created_at' => '2023-06-06 18:10:05',
                'updated_at' => '2023-06-06 18:10:19',
            ),
            7 => 
            array (
                'id' => 87,
                'code' => 'CE140',
                'subject' => 'Hydraulics',
                'unit' => 3,
                'is_lab' => 0,
                'is_nonacademic' => 0,
                'is_failed' => 0,
                'grade' => '1',
                'enrollment_id' => 9,
                'encoded_by' => 1,
                'options' => '[]',
                'created_at' => '2023-06-06 18:10:05',
                'updated_at' => '2023-06-06 18:10:19',
            ),
            8 => 
            array (
                'id' => 88,
                'code' => 'CE140',
                'subject' => 'Hydraulics',
                'unit' => 2,
                'is_lab' => 1,
                'is_nonacademic' => 0,
                'is_failed' => 0,
                'grade' => '1',
                'enrollment_id' => 9,
                'encoded_by' => 1,
                'options' => '[]',
                'created_at' => '2023-06-06 18:10:05',
                'updated_at' => '2023-06-06 18:10:19',
            ),
            9 => 
            array (
                'id' => 89,
                'code' => 'CEL132',
                'subject' => 'CE Laws, Ethics and Contracts',
                'unit' => 2,
                'is_lab' => 0,
                'is_nonacademic' => 0,
                'is_failed' => 0,
                'grade' => '1',
                'enrollment_id' => 9,
                'encoded_by' => 1,
                'options' => '[]',
                'created_at' => '2023-06-06 18:10:05',
                'updated_at' => '2023-06-06 18:10:19',
            ),
            10 => 
            array (
                'id' => 90,
                'code' => 'HIST101',
                'subject' => 'Readings in Philippine History',
                'unit' => 3,
                'is_lab' => 0,
                'is_nonacademic' => 0,
                'is_failed' => 0,
                'grade' => '1',
                'enrollment_id' => 9,
                'encoded_by' => 1,
                'options' => '[]',
                'created_at' => '2023-06-06 18:10:05',
                'updated_at' => '2023-06-06 18:10:19',
            ),
            11 => 
            array (
                'id' => 91,
                'code' => 'A&H100',
                'subject' => 'Art Appreciation',
                'unit' => 3,
                'is_lab' => 0,
                'is_nonacademic' => 0,
                'is_failed' => 0,
                'grade' => '1',
                'enrollment_id' => 9,
                'encoded_by' => 1,
                'options' => '[]',
                'created_at' => '2023-06-06 18:10:05',
                'updated_at' => '2023-06-06 18:10:19',
            ),
            12 => 
            array (
                'id' => 92,
                'code' => 'CE139',
            'subject' => 'On The Job Training (240hrs)',
                'unit' => 3,
                'is_lab' => 0,
                'is_nonacademic' => 0,
                'is_failed' => 0,
                'grade' => '1',
                'enrollment_id' => 10,
                'encoded_by' => 1,
                'options' => '[]',
                'created_at' => '2023-06-06 18:11:06',
                'updated_at' => '2023-06-06 18:11:18',
            ),
            13 => 
            array (
                'id' => 93,
                'code' => 'CE141',
                'subject' => 'CE Project 1',
                'unit' => 2,
                'is_lab' => 0,
                'is_nonacademic' => 0,
                'is_failed' => 0,
                'grade' => '1',
                'enrollment_id' => 11,
                'encoded_by' => 1,
                'options' => '[]',
                'created_at' => '2023-06-06 18:12:06',
                'updated_at' => '2023-06-06 18:12:24',
            ),
            14 => 
            array (
                'id' => 94,
                'code' => 'CE143',
                'subject' => 'Principles of Steel Design',
                'unit' => 2,
                'is_lab' => 0,
                'is_nonacademic' => 0,
                'is_failed' => 0,
                'grade' => '1',
                'enrollment_id' => 11,
                'encoded_by' => 1,
                'options' => '[]',
                'created_at' => '2023-06-06 18:12:06',
                'updated_at' => '2023-06-06 18:12:24',
            ),
            15 => 
            array (
                'id' => 95,
                'code' => 'CE143',
                'subject' => 'Principles of Steel Design',
                'unit' => 1,
                'is_lab' => 1,
                'is_nonacademic' => 0,
                'is_failed' => 0,
                'grade' => '1',
                'enrollment_id' => 11,
                'encoded_by' => 1,
                'options' => '[]',
                'created_at' => '2023-06-06 18:12:06',
                'updated_at' => '2023-06-06 18:12:24',
            ),
            16 => 
            array (
                'id' => 96,
                'code' => 'CE145',
                'subject' => 'Foundation Engineering',
                'unit' => 3,
                'is_lab' => 0,
                'is_nonacademic' => 0,
                'is_failed' => 0,
                'grade' => '1',
                'enrollment_id' => 11,
                'encoded_by' => 1,
                'options' => '[]',
                'created_at' => '2023-06-06 18:12:06',
                'updated_at' => '2023-06-06 18:12:24',
            ),
            17 => 
            array (
                'id' => 97,
                'code' => 'CES141',
                'subject' => 'Water Resource Engineering',
                'unit' => 3,
                'is_lab' => 0,
                'is_nonacademic' => 0,
                'is_failed' => 0,
                'grade' => '1',
                'enrollment_id' => 11,
                'encoded_by' => 1,
                'options' => '[]',
                'created_at' => '2023-06-06 18:12:06',
                'updated_at' => '2023-06-06 18:12:24',
            ),
            18 => 
            array (
                'id' => 98,
                'code' => 'CES143',
                'subject' => 'Water Supply Planning & Development',
                'unit' => 3,
                'is_lab' => 0,
                'is_nonacademic' => 0,
                'is_failed' => 0,
                'grade' => '1',
                'enrollment_id' => 11,
                'encoded_by' => 1,
                'options' => '[]',
                'created_at' => '2023-06-06 18:12:06',
                'updated_at' => '2023-06-06 18:12:24',
            ),
            19 => 
            array (
                'id' => 99,
                'code' => 'CES145',
                'subject' => 'Flood Control & Drainage System',
                'unit' => 3,
                'is_lab' => 0,
                'is_nonacademic' => 0,
                'is_failed' => 0,
                'grade' => '1',
                'enrollment_id' => 11,
                'encoded_by' => 1,
                'options' => '[]',
                'created_at' => '2023-06-06 18:12:06',
                'updated_at' => '2023-06-06 18:12:24',
            ),
            20 => 
            array (
                'id' => 100,
                'code' => 'CE147',
                'subject' => 'CE Practice 1',
                'unit' => 3,
                'is_lab' => 0,
                'is_nonacademic' => 0,
                'is_failed' => 0,
                'grade' => '1',
                'enrollment_id' => 11,
                'encoded_by' => 1,
                'options' => '[]',
                'created_at' => '2023-06-06 18:12:06',
                'updated_at' => '2023-06-06 18:12:24',
            ),
            21 => 
            array (
                'id' => 101,
                'code' => 'CE147',
                'subject' => 'CE Practice 1',
                'unit' => 1,
                'is_lab' => 1,
                'is_nonacademic' => 0,
                'is_failed' => 0,
                'grade' => '1',
                'enrollment_id' => 11,
                'encoded_by' => 1,
                'options' => '[]',
                'created_at' => '2023-06-06 18:12:06',
                'updated_at' => '2023-06-06 18:12:24',
            ),
            22 => 
            array (
                'id' => 102,
                'code' => 'CE142',
                'subject' => 'CE Project 2',
                'unit' => 2,
                'is_lab' => 1,
                'is_nonacademic' => 0,
                'is_failed' => 0,
                'grade' => '1',
                'enrollment_id' => 12,
                'encoded_by' => 1,
                'options' => '[]',
                'created_at' => '2023-06-06 18:12:53',
                'updated_at' => '2023-06-06 18:13:11',
            ),
            23 => 
            array (
                'id' => 103,
                'code' => 'CE144',
                'subject' => 'Quantity Surveying',
                'unit' => 2,
                'is_lab' => 1,
                'is_nonacademic' => 0,
                'is_failed' => 0,
                'grade' => '1',
                'enrollment_id' => 12,
                'encoded_by' => 1,
                'options' => '[]',
                'created_at' => '2023-06-06 18:12:53',
                'updated_at' => '2023-06-06 18:13:11',
            ),
            24 => 
            array (
                'id' => 104,
                'code' => 'CES142',
                'subject' => 'Irrigation Engineering',
                'unit' => 3,
                'is_lab' => 0,
                'is_nonacademic' => 0,
                'is_failed' => 0,
                'grade' => '1',
                'enrollment_id' => 12,
                'encoded_by' => 1,
                'options' => '[]',
                'created_at' => '2023-06-06 18:12:53',
                'updated_at' => '2023-06-06 18:13:11',
            ),
            25 => 
            array (
                'id' => 105,
                'code' => 'CES144',
                'subject' => 'Coastal Engineering',
                'unit' => 3,
                'is_lab' => 0,
                'is_nonacademic' => 0,
                'is_failed' => 0,
                'grade' => '1',
                'enrollment_id' => 12,
                'encoded_by' => 1,
                'options' => '[]',
                'created_at' => '2023-06-06 18:12:53',
                'updated_at' => '2023-06-06 18:13:11',
            ),
            26 => 
            array (
                'id' => 106,
                'code' => 'CES146',
                'subject' => 'River Engineering',
                'unit' => 3,
                'is_lab' => 0,
                'is_nonacademic' => 0,
                'is_failed' => 0,
                'grade' => '1',
                'enrollment_id' => 12,
                'encoded_by' => 1,
                'options' => '[]',
                'created_at' => '2023-06-06 18:12:53',
                'updated_at' => '2023-06-06 18:13:11',
            ),
            27 => 
            array (
                'id' => 107,
                'code' => 'CES148',
                'subject' => 'Ground Water Flow Modelling',
                'unit' => 3,
                'is_lab' => 0,
                'is_nonacademic' => 0,
                'is_failed' => 0,
                'grade' => '1',
                'enrollment_id' => 12,
                'encoded_by' => 1,
                'options' => '[]',
                'created_at' => '2023-06-06 18:12:53',
                'updated_at' => '2023-06-06 18:13:11',
            ),
            28 => 
            array (
                'id' => 108,
                'code' => 'CE146',
                'subject' => 'CE Practice 2',
                'unit' => 3,
                'is_lab' => 0,
                'is_nonacademic' => 0,
                'is_failed' => 0,
                'grade' => '1',
                'enrollment_id' => 12,
                'encoded_by' => 1,
                'options' => '[]',
                'created_at' => '2023-06-06 18:12:53',
                'updated_at' => '2023-06-06 18:13:11',
            ),
            29 => 
            array (
                'id' => 109,
                'code' => 'CE146',
                'subject' => 'CE Practice 2',
                'unit' => 1,
                'is_lab' => 1,
                'is_nonacademic' => 0,
                'is_failed' => 0,
                'grade' => '1',
                'enrollment_id' => 12,
                'encoded_by' => 1,
                'options' => '[]',
                'created_at' => '2023-06-06 18:12:53',
                'updated_at' => '2023-06-06 18:13:11',
            ),
            30 => 
            array (
                'id' => 110,
                'code' => 'BEM122',
                'subject' => 'Advanced Mathematics for CE',
                'unit' => 3,
                'is_lab' => 0,
                'is_nonacademic' => 0,
                'is_failed' => NULL,
                'grade' => NULL,
                'enrollment_id' => 13,
                'encoded_by' => 1,
                'options' => '[]',
                'created_at' => '2023-06-07 07:51:53',
                'updated_at' => '2023-06-07 07:51:53',
            ),
            31 => 
            array (
                'id' => 111,
                'code' => 'BES122',
                'subject' => 'Dynamic of Rigid Bodies',
                'unit' => 2,
                'is_lab' => 0,
                'is_nonacademic' => 0,
                'is_failed' => NULL,
                'grade' => NULL,
                'enrollment_id' => 13,
                'encoded_by' => 1,
                'options' => '[]',
                'created_at' => '2023-06-07 07:51:53',
                'updated_at' => '2023-06-07 07:51:53',
            ),
            32 => 
            array (
                'id' => 112,
                'code' => 'BES124',
                'subject' => 'Mechanics of Deformable Bodies',
                'unit' => 4,
                'is_lab' => 0,
                'is_nonacademic' => 0,
                'is_failed' => NULL,
                'grade' => NULL,
                'enrollment_id' => 13,
                'encoded_by' => 1,
                'options' => '[]',
                'created_at' => '2023-06-07 07:51:53',
                'updated_at' => '2023-06-07 07:51:53',
            ),
            33 => 
            array (
                'id' => 113,
                'code' => 'CE122',
                'subject' => 'Construction Materials & Tesing',
                'unit' => 2,
                'is_lab' => 0,
                'is_nonacademic' => 0,
                'is_failed' => NULL,
                'grade' => NULL,
                'enrollment_id' => 13,
                'encoded_by' => 1,
                'options' => '[]',
                'created_at' => '2023-06-07 07:51:53',
                'updated_at' => '2023-06-07 07:51:53',
            ),
            34 => 
            array (
                'id' => 114,
                'code' => 'CE122',
                'subject' => 'Construction Materials & Tesing',
                'unit' => 1,
                'is_lab' => 1,
                'is_nonacademic' => 0,
                'is_failed' => NULL,
                'grade' => NULL,
                'enrollment_id' => 13,
                'encoded_by' => 1,
                'options' => '[]',
                'created_at' => '2023-06-07 07:51:53',
                'updated_at' => '2023-06-07 07:51:53',
            ),
            35 => 
            array (
                'id' => 115,
                'code' => 'CE124',
                'subject' => 'Excel VBA Programming and MATLAB',
                'unit' => 1,
                'is_lab' => 1,
                'is_nonacademic' => 0,
                'is_failed' => NULL,
                'grade' => NULL,
                'enrollment_id' => 13,
                'encoded_by' => 1,
                'options' => '[]',
                'created_at' => '2023-06-07 07:51:53',
                'updated_at' => '2023-06-07 07:51:53',
            ),
            36 => 
            array (
                'id' => 116,
                'code' => 'BES126',
                'subject' => 'Engineering Management',
                'unit' => 2,
                'is_lab' => 0,
                'is_nonacademic' => 0,
                'is_failed' => NULL,
                'grade' => NULL,
                'enrollment_id' => 13,
                'encoded_by' => 1,
                'options' => '[]',
                'created_at' => '2023-06-07 07:51:53',
                'updated_at' => '2023-06-07 07:51:53',
            ),
            37 => 
            array (
                'id' => 117,
                'code' => 'CW101',
                'subject' => 'The Contemporary World',
                'unit' => 3,
                'is_lab' => 0,
                'is_nonacademic' => 0,
                'is_failed' => NULL,
                'grade' => NULL,
                'enrollment_id' => 13,
                'encoded_by' => 1,
                'options' => '[]',
                'created_at' => '2023-06-07 07:51:53',
                'updated_at' => '2023-06-07 07:51:53',
            ),
            38 => 
            array (
                'id' => 118,
                'code' => 'PE104',
                'subject' => 'Physical Education 4',
                'unit' => 2,
                'is_lab' => 0,
                'is_nonacademic' => 0,
                'is_failed' => NULL,
                'grade' => NULL,
                'enrollment_id' => 13,
                'encoded_by' => 1,
                'options' => '[]',
                'created_at' => '2023-06-07 07:51:53',
                'updated_at' => '2023-06-07 07:51:53',
            ),
            39 => 
            array (
                'id' => 119,
                'code' => 'EPIC4',
                'subject' => 'Epic',
                'unit' => 3,
                'is_lab' => 0,
                'is_nonacademic' => 0,
                'is_failed' => NULL,
                'grade' => NULL,
                'enrollment_id' => 13,
                'encoded_by' => 1,
                'options' => '[]',
                'created_at' => '2023-06-07 07:51:53',
                'updated_at' => '2023-06-07 07:51:53',
            ),
            40 => 
            array (
                'id' => 120,
                'code' => 'BEM112',
                'subject' => 'Engineering calculus 2',
                'unit' => 3,
                'is_lab' => 0,
                'is_nonacademic' => 0,
                'is_failed' => NULL,
                'grade' => NULL,
                'enrollment_id' => 14,
                'encoded_by' => 1,
                'options' => '[]',
                'created_at' => '2023-06-07 07:56:16',
                'updated_at' => '2023-06-07 07:56:16',
            ),
            41 => 
            array (
                'id' => 121,
                'code' => 'CE112',
                'subject' => 'Civil Engineering Orientation',
                'unit' => 2,
                'is_lab' => 0,
                'is_nonacademic' => 0,
                'is_failed' => NULL,
                'grade' => NULL,
                'enrollment_id' => 14,
                'encoded_by' => 1,
                'options' => '[]',
                'created_at' => '2023-06-07 07:56:16',
                'updated_at' => '2023-06-07 07:56:16',
            ),
            42 => 
            array (
                'id' => 122,
                'code' => 'BES112',
                'subject' => 'physics for engineer',
                'unit' => 3,
                'is_lab' => 0,
                'is_nonacademic' => 0,
                'is_failed' => NULL,
                'grade' => NULL,
                'enrollment_id' => 14,
                'encoded_by' => 1,
                'options' => '[]',
                'created_at' => '2023-06-07 07:56:16',
                'updated_at' => '2023-06-07 07:56:16',
            ),
            43 => 
            array (
                'id' => 123,
                'code' => 'BES112',
                'subject' => 'physics for engineer',
                'unit' => 1,
                'is_lab' => 1,
                'is_nonacademic' => 0,
                'is_failed' => NULL,
                'grade' => NULL,
                'enrollment_id' => 14,
                'encoded_by' => 1,
                'options' => '[]',
                'created_at' => '2023-06-07 07:56:16',
                'updated_at' => '2023-06-07 07:56:16',
            ),
            44 => 
            array (
                'id' => 124,
                'code' => 'FIL102',
                'subject' => 'Retorika',
                'unit' => 3,
                'is_lab' => 0,
                'is_nonacademic' => 0,
                'is_failed' => NULL,
                'grade' => NULL,
                'enrollment_id' => 14,
                'encoded_by' => 1,
                'options' => '[]',
                'created_at' => '2023-06-07 07:56:16',
                'updated_at' => '2023-06-07 07:56:16',
            ),
            45 => 
            array (
                'id' => 125,
                'code' => 'PE102',
                'subject' => 'Physical Education 2',
                'unit' => 2,
                'is_lab' => 0,
                'is_nonacademic' => 1,
                'is_failed' => NULL,
                'grade' => NULL,
                'enrollment_id' => 14,
                'encoded_by' => 1,
                'options' => '[]',
                'created_at' => '2023-06-07 07:56:16',
                'updated_at' => '2023-06-07 07:56:16',
            ),
            46 => 
            array (
                'id' => 126,
                'code' => 'NSTP2',
                'subject' => 'National Service Training Program',
                'unit' => 3,
                'is_lab' => 0,
                'is_nonacademic' => 1,
                'is_failed' => NULL,
                'grade' => NULL,
                'enrollment_id' => 14,
                'encoded_by' => 1,
                'options' => '[]',
                'created_at' => '2023-06-07 07:56:16',
                'updated_at' => '2023-06-07 07:56:16',
            ),
            47 => 
            array (
                'id' => 127,
                'code' => 'EPIC2',
                'subject' => 'Epic',
                'unit' => 3,
                'is_lab' => 0,
                'is_nonacademic' => 0,
                'is_failed' => NULL,
                'grade' => NULL,
                'enrollment_id' => 14,
                'encoded_by' => 1,
                'options' => '[]',
                'created_at' => '2023-06-07 07:56:16',
                'updated_at' => '2023-06-07 07:56:16',
            ),
            48 => 
            array (
                'id' => 128,
                'code' => 'BEM114',
                'subject' => 'Engineering data analysis',
                'unit' => 3,
                'is_lab' => 0,
                'is_nonacademic' => 0,
                'is_failed' => NULL,
                'grade' => NULL,
                'enrollment_id' => 14,
                'encoded_by' => 1,
                'options' => '[]',
                'created_at' => '2023-06-07 07:56:16',
                'updated_at' => '2023-06-07 07:56:16',
            ),
            49 => 
            array (
                'id' => 129,
                'code' => 'CE114',
                'subject' => 'Geology for Civil Engineers',
                'unit' => 2,
                'is_lab' => 0,
                'is_nonacademic' => 0,
                'is_failed' => NULL,
                'grade' => NULL,
                'enrollment_id' => 14,
                'encoded_by' => 1,
                'options' => '[]',
                'created_at' => '2023-06-07 07:56:16',
                'updated_at' => '2023-06-07 07:56:16',
            ),
            50 => 
            array (
                'id' => 130,
                'code' => 'BES115',
                'subject' => 'Computer Fundamentals & Programming',
                'unit' => 2,
                'is_lab' => 1,
                'is_nonacademic' => 0,
                'is_failed' => NULL,
                'grade' => NULL,
                'enrollment_id' => 14,
                'encoded_by' => 1,
                'options' => '[]',
                'created_at' => '2023-06-07 07:56:16',
                'updated_at' => '2023-06-07 07:56:16',
            ),
        ));
        
        
    }
}