<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class ScholarBenefitsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('scholar_benefits')->delete();
        
        \DB::table('scholar_benefits')->insert(array (
            0 => 
            array (
                'id' => 50,
                'amount' => '7000.00',
                'release_type' => 'Full',
                'dv_no' => NULL,
                'month' => '2021-01-01',
                'attachment' => '[]',
                'is_reimbursed' => 0,
                'status_id' => 12,
                'benefit_id' => 1,
                'scholar_id' => 914,
                'release_id' => 1,
                'school_semester_id' => 1,
            ),
            1 => 
            array (
                'id' => 51,
                'amount' => '7000.00',
                'release_type' => 'Full',
                'dv_no' => NULL,
                'month' => '2021-02-01',
                'attachment' => '[]',
                'is_reimbursed' => 0,
                'status_id' => 12,
                'benefit_id' => 1,
                'scholar_id' => 914,
                'release_id' => 1,
                'school_semester_id' => 1,
            ),
            2 => 
            array (
                'id' => 52,
                'amount' => '7000.00',
                'release_type' => 'Full',
                'dv_no' => NULL,
                'month' => '2021-03-01',
                'attachment' => '[]',
                'is_reimbursed' => 0,
                'status_id' => 12,
                'benefit_id' => 1,
                'scholar_id' => 914,
                'release_id' => 1,
                'school_semester_id' => 1,
            ),
            3 => 
            array (
                'id' => 53,
                'amount' => '7000.00',
                'release_type' => 'Full',
                'dv_no' => NULL,
                'month' => '2021-04-01',
                'attachment' => '[]',
                'is_reimbursed' => 0,
                'status_id' => 12,
                'benefit_id' => 1,
                'scholar_id' => 914,
                'release_id' => 1,
                'school_semester_id' => 1,
            ),
            4 => 
            array (
                'id' => 54,
                'amount' => '7000.00',
                'release_type' => 'Full',
                'dv_no' => NULL,
                'month' => '2021-05-01',
                'attachment' => '[]',
                'is_reimbursed' => 0,
                'status_id' => 12,
                'benefit_id' => 1,
                'scholar_id' => 914,
                'release_id' => 1,
                'school_semester_id' => 1,
            ),
            5 => 
            array (
                'id' => 55,
                'amount' => '5000.00',
                'release_type' => 'Full',
                'dv_no' => NULL,
                'month' => '2021-01-01',
                'attachment' => '[]',
                'is_reimbursed' => 0,
                'status_id' => 12,
                'benefit_id' => 3,
                'scholar_id' => 914,
                'release_id' => 1,
                'school_semester_id' => 1,
            ),
            6 => 
            array (
                'id' => 57,
                'amount' => '7000.00',
                'release_type' => 'Full',
                'dv_no' => NULL,
                'month' => '2021-06-01',
                'attachment' => '[]',
                'is_reimbursed' => 0,
                'status_id' => 12,
                'benefit_id' => 1,
                'scholar_id' => 914,
                'release_id' => 1,
                'school_semester_id' => 2,
            ),
            7 => 
            array (
                'id' => 58,
                'amount' => '7000.00',
                'release_type' => 'Full',
                'dv_no' => NULL,
                'month' => '2021-07-01',
                'attachment' => '[]',
                'is_reimbursed' => 0,
                'status_id' => 12,
                'benefit_id' => 1,
                'scholar_id' => 914,
                'release_id' => 1,
                'school_semester_id' => 2,
            ),
            8 => 
            array (
                'id' => 62,
                'amount' => '2000.00',
                'release_type' => 'Full',
                'dv_no' => NULL,
                'month' => '2021-06-01',
                'attachment' => '[]',
                'is_reimbursed' => 0,
                'status_id' => 12,
                'benefit_id' => 3,
                'scholar_id' => 914,
                'release_id' => 1,
                'school_semester_id' => 2,
            ),
            9 => 
            array (
                'id' => 63,
                'amount' => '7000.00',
                'release_type' => 'Full',
                'dv_no' => NULL,
                'month' => '2022-01-01',
                'attachment' => '[]',
                'is_reimbursed' => 0,
                'status_id' => 12,
                'benefit_id' => 1,
                'scholar_id' => 914,
                'release_id' => 1,
                'school_semester_id' => 3,
            ),
            10 => 
            array (
                'id' => 64,
                'amount' => '7000.00',
                'release_type' => 'Full',
                'dv_no' => NULL,
                'month' => '2022-02-01',
                'attachment' => '[]',
                'is_reimbursed' => 0,
                'status_id' => 12,
                'benefit_id' => 1,
                'scholar_id' => 914,
                'release_id' => 1,
                'school_semester_id' => 3,
            ),
            11 => 
            array (
                'id' => 65,
                'amount' => '7000.00',
                'release_type' => 'Full',
                'dv_no' => NULL,
                'month' => '2022-03-01',
                'attachment' => '[]',
                'is_reimbursed' => 0,
                'status_id' => 12,
                'benefit_id' => 1,
                'scholar_id' => 914,
                'release_id' => 1,
                'school_semester_id' => 3,
            ),
            12 => 
            array (
                'id' => 66,
                'amount' => '7000.00',
                'release_type' => 'Full',
                'dv_no' => NULL,
                'month' => '2022-04-01',
                'attachment' => '[]',
                'is_reimbursed' => 0,
                'status_id' => 12,
                'benefit_id' => 1,
                'scholar_id' => 914,
                'release_id' => 1,
                'school_semester_id' => 3,
            ),
            13 => 
            array (
                'id' => 67,
                'amount' => '7000.00',
                'release_type' => 'Full',
                'dv_no' => NULL,
                'month' => '2022-05-01',
                'attachment' => '[]',
                'is_reimbursed' => 0,
                'status_id' => 12,
                'benefit_id' => 1,
                'scholar_id' => 914,
                'release_id' => 1,
                'school_semester_id' => 3,
            ),
            14 => 
            array (
                'id' => 68,
                'amount' => '5000.00',
                'release_type' => 'Full',
                'dv_no' => NULL,
                'month' => '2022-01-01',
                'attachment' => '[]',
                'is_reimbursed' => 0,
                'status_id' => 12,
                'benefit_id' => 3,
                'scholar_id' => 914,
                'release_id' => 1,
                'school_semester_id' => 3,
            ),
            15 => 
            array (
                'id' => 69,
                'amount' => '7000.00',
                'release_type' => 'Full',
                'dv_no' => NULL,
                'month' => '2022-08-01',
                'attachment' => '[]',
                'is_reimbursed' => 0,
                'status_id' => 12,
                'benefit_id' => 1,
                'scholar_id' => 914,
                'release_id' => 1,
                'school_semester_id' => 4,
            ),
            16 => 
            array (
                'id' => 70,
                'amount' => '7000.00',
                'release_type' => 'Full',
                'dv_no' => NULL,
                'month' => '2022-09-01',
                'attachment' => '[]',
                'is_reimbursed' => 0,
                'status_id' => 12,
                'benefit_id' => 1,
                'scholar_id' => 914,
                'release_id' => 1,
                'school_semester_id' => 4,
            ),
            17 => 
            array (
                'id' => 71,
                'amount' => '7000.00',
                'release_type' => 'Full',
                'dv_no' => NULL,
                'month' => '2022-10-01',
                'attachment' => '[]',
                'is_reimbursed' => 0,
                'status_id' => 12,
                'benefit_id' => 1,
                'scholar_id' => 914,
                'release_id' => 1,
                'school_semester_id' => 4,
            ),
            18 => 
            array (
                'id' => 72,
                'amount' => '7000.00',
                'release_type' => 'Full',
                'dv_no' => NULL,
                'month' => '2022-11-01',
                'attachment' => '[]',
                'is_reimbursed' => 0,
                'status_id' => 12,
                'benefit_id' => 1,
                'scholar_id' => 914,
                'release_id' => 1,
                'school_semester_id' => 4,
            ),
            19 => 
            array (
                'id' => 73,
                'amount' => '7000.00',
                'release_type' => 'Full',
                'dv_no' => NULL,
                'month' => '2022-12-01',
                'attachment' => '[]',
                'is_reimbursed' => 0,
                'status_id' => 12,
                'benefit_id' => 1,
                'scholar_id' => 914,
                'release_id' => 1,
                'school_semester_id' => 4,
            ),
            20 => 
            array (
                'id' => 74,
                'amount' => '5000.00',
                'release_type' => 'Full',
                'dv_no' => NULL,
                'month' => '2022-08-01',
                'attachment' => '[]',
                'is_reimbursed' => 0,
                'status_id' => 12,
                'benefit_id' => 3,
                'scholar_id' => 914,
                'release_id' => 1,
                'school_semester_id' => 4,
            ),
            21 => 
            array (
                'id' => 75,
                'amount' => '7000.00',
                'release_type' => 'Full',
                'dv_no' => NULL,
                'month' => '2022-08-01',
                'attachment' => '[]',
                'is_reimbursed' => 0,
                'status_id' => 12,
                'benefit_id' => 1,
                'scholar_id' => 965,
                'release_id' => 1,
                'school_semester_id' => 4,
            ),
            22 => 
            array (
                'id' => 76,
                'amount' => '7000.00',
                'release_type' => 'Full',
                'dv_no' => NULL,
                'month' => '2022-09-01',
                'attachment' => '[]',
                'is_reimbursed' => 0,
                'status_id' => 12,
                'benefit_id' => 1,
                'scholar_id' => 965,
                'release_id' => 1,
                'school_semester_id' => 4,
            ),
            23 => 
            array (
                'id' => 77,
                'amount' => '7000.00',
                'release_type' => 'Full',
                'dv_no' => NULL,
                'month' => '2022-10-01',
                'attachment' => '[]',
                'is_reimbursed' => 0,
                'status_id' => 12,
                'benefit_id' => 1,
                'scholar_id' => 965,
                'release_id' => 1,
                'school_semester_id' => 4,
            ),
            24 => 
            array (
                'id' => 78,
                'amount' => '7000.00',
                'release_type' => 'Full',
                'dv_no' => NULL,
                'month' => '2022-11-01',
                'attachment' => '[]',
                'is_reimbursed' => 0,
                'status_id' => 12,
                'benefit_id' => 1,
                'scholar_id' => 965,
                'release_id' => 1,
                'school_semester_id' => 4,
            ),
            25 => 
            array (
                'id' => 79,
                'amount' => '7000.00',
                'release_type' => 'Full',
                'dv_no' => NULL,
                'month' => '2022-12-01',
                'attachment' => '[]',
                'is_reimbursed' => 0,
                'status_id' => 12,
                'benefit_id' => 1,
                'scholar_id' => 965,
                'release_id' => 1,
                'school_semester_id' => 4,
            ),
            26 => 
            array (
                'id' => 80,
                'amount' => '5000.00',
                'release_type' => 'Full',
                'dv_no' => NULL,
                'month' => '2022-08-01',
                'attachment' => '[]',
                'is_reimbursed' => 0,
                'status_id' => 12,
                'benefit_id' => 3,
                'scholar_id' => 965,
                'release_id' => 1,
                'school_semester_id' => 4,
            ),
            27 => 
            array (
                'id' => 82,
                'amount' => '7000.00',
                'release_type' => 'Full',
                'dv_no' => NULL,
                'month' => '2022-08-01',
                'attachment' => '[]',
                'is_reimbursed' => 0,
                'status_id' => 12,
                'benefit_id' => 1,
                'scholar_id' => 937,
                'release_id' => 1,
                'school_semester_id' => 4,
            ),
            28 => 
            array (
                'id' => 83,
                'amount' => '7000.00',
                'release_type' => 'Full',
                'dv_no' => NULL,
                'month' => '2022-09-01',
                'attachment' => '[]',
                'is_reimbursed' => 0,
                'status_id' => 12,
                'benefit_id' => 1,
                'scholar_id' => 937,
                'release_id' => 1,
                'school_semester_id' => 4,
            ),
            29 => 
            array (
                'id' => 84,
                'amount' => '7000.00',
                'release_type' => 'Full',
                'dv_no' => NULL,
                'month' => '2022-10-01',
                'attachment' => '[]',
                'is_reimbursed' => 0,
                'status_id' => 12,
                'benefit_id' => 1,
                'scholar_id' => 937,
                'release_id' => 1,
                'school_semester_id' => 4,
            ),
            30 => 
            array (
                'id' => 85,
                'amount' => '7000.00',
                'release_type' => 'Full',
                'dv_no' => NULL,
                'month' => '2022-11-01',
                'attachment' => '[]',
                'is_reimbursed' => 0,
                'status_id' => 12,
                'benefit_id' => 1,
                'scholar_id' => 937,
                'release_id' => 1,
                'school_semester_id' => 4,
            ),
            31 => 
            array (
                'id' => 86,
                'amount' => '7000.00',
                'release_type' => 'Full',
                'dv_no' => NULL,
                'month' => '2022-12-01',
                'attachment' => '[]',
                'is_reimbursed' => 0,
                'status_id' => 12,
                'benefit_id' => 1,
                'scholar_id' => 937,
                'release_id' => 1,
                'school_semester_id' => 4,
            ),
            32 => 
            array (
                'id' => 87,
                'amount' => '5000.00',
                'release_type' => 'Full',
                'dv_no' => NULL,
                'month' => '2022-08-01',
                'attachment' => '[]',
                'is_reimbursed' => 0,
                'status_id' => 12,
                'benefit_id' => 3,
                'scholar_id' => 937,
                'release_id' => 1,
                'school_semester_id' => 4,
            ),
            33 => 
            array (
                'id' => 89,
                'amount' => '1000.00',
                'release_type' => 'Full',
                'dv_no' => NULL,
                'month' => '2023-06-07',
                'attachment' => '[{"file": "reimbursements/reimbursement_23-06-07083835.pdf", "name": "reimbursement_23-06-07083835.pdf", "added_by": 1, "created_at": "Jun 07, 2023 8:38 am"}]',
                'is_reimbursed' => 1,
                'status_id' => 12,
                'benefit_id' => 6,
                'scholar_id' => 1001,
                'release_id' => 1,
                'school_semester_id' => 1,
            ),
            34 => 
            array (
                'id' => 90,
                'amount' => '9000.00',
                'release_type' => 'Full',
                'dv_no' => NULL,
                'month' => '2023-06-07',
                'attachment' => '[{"file": "reimbursements/reimbursement_23-06-07084220.pdf", "name": "reimbursement_23-06-07084220.pdf", "added_by": 1, "created_at": "Jun 07, 2023 8:42 am"}]',
                'is_reimbursed' => 1,
                'status_id' => 12,
                'benefit_id' => 6,
                'scholar_id' => 901,
                'release_id' => 1,
                'school_semester_id' => 1,
            ),
            35 => 
            array (
                'id' => 91,
                'amount' => '1000.00',
                'release_type' => 'Full',
                'dv_no' => NULL,
                'month' => '2023-06-07',
                'attachment' => '[{"file": "reimbursements/reimbursement_23-06-07084516.pdf", "name": "reimbursement_23-06-07084516.pdf", "added_by": 1, "created_at": "Jun 07, 2023 8:45 am"}]',
                'is_reimbursed' => 1,
                'status_id' => 12,
                'benefit_id' => 6,
                'scholar_id' => 903,
                'release_id' => 1,
                'school_semester_id' => 1,
            ),
            36 => 
            array (
                'id' => 92,
                'amount' => '1000.00',
                'release_type' => 'Full',
                'dv_no' => NULL,
                'month' => '2023-06-07',
                'attachment' => '[{"file": "reimbursements/reimbursement_23-06-07084644.pdf", "name": "reimbursement_23-06-07084644.pdf", "added_by": 1, "created_at": "Jun 07, 2023 8:46 am"}]',
                'is_reimbursed' => 1,
                'status_id' => 12,
                'benefit_id' => 6,
                'scholar_id' => 904,
                'release_id' => 1,
                'school_semester_id' => 1,
            ),
            37 => 
            array (
                'id' => 93,
                'amount' => '1000.00',
                'release_type' => 'Full',
                'dv_no' => NULL,
                'month' => '2023-06-07',
                'attachment' => '[{"file": "reimbursements/reimbursement_23-06-07084826.pdf", "name": "reimbursement_23-06-07084826.pdf", "added_by": 1, "created_at": "Jun 07, 2023 8:48 am"}]',
                'is_reimbursed' => 1,
                'status_id' => 12,
                'benefit_id' => 6,
                'scholar_id' => 910,
                'release_id' => 1,
                'school_semester_id' => 1,
            ),
            38 => 
            array (
                'id' => 94,
                'amount' => '1000.00',
                'release_type' => 'Full',
                'dv_no' => NULL,
                'month' => '2023-06-07',
                'attachment' => '[{"file": "reimbursements/reimbursement_23-06-07084932.pdf", "name": "reimbursement_23-06-07084932.pdf", "added_by": 1, "created_at": "Jun 07, 2023 8:49 am"}]',
                'is_reimbursed' => 1,
                'status_id' => 12,
                'benefit_id' => 6,
                'scholar_id' => 1010,
                'release_id' => 1,
                'school_semester_id' => 1,
            ),
            39 => 
            array (
                'id' => 95,
                'amount' => '1000.00',
                'release_type' => 'Full',
                'dv_no' => NULL,
                'month' => '2023-06-07',
                'attachment' => '[{"file": "reimbursements/reimbursement_23-06-07085008.pdf", "name": "reimbursement_23-06-07085008.pdf", "added_by": 1, "created_at": "Jun 07, 2023 8:50 am"}]',
                'is_reimbursed' => 1,
                'status_id' => 12,
                'benefit_id' => 7,
                'scholar_id' => 852,
                'release_id' => 1,
                'school_semester_id' => 1,
            ),
            40 => 
            array (
                'id' => 96,
                'amount' => '1000.00',
                'release_type' => 'Full',
                'dv_no' => NULL,
                'month' => '2023-06-07',
                'attachment' => '[{"file": "reimbursements/reimbursement_23-06-07085147.pdf", "name": "reimbursement_23-06-07085147.pdf", "added_by": 1, "created_at": "Jun 07, 2023 8:51 am"}]',
                'is_reimbursed' => 1,
                'status_id' => 12,
                'benefit_id' => 6,
                'scholar_id' => 920,
                'release_id' => 1,
                'school_semester_id' => 1,
            ),
            41 => 
            array (
                'id' => 97,
                'amount' => '9000.00',
                'release_type' => 'Full',
                'dv_no' => NULL,
                'month' => '2023-06-07',
                'attachment' => '[{"file": "reimbursements/reimbursement_23-06-07085216.pdf", "name": "reimbursement_23-06-07085216.pdf", "added_by": 1, "created_at": "Jun 07, 2023 8:52 am"}]',
                'is_reimbursed' => 1,
                'status_id' => 12,
                'benefit_id' => 6,
                'scholar_id' => 921,
                'release_id' => 1,
                'school_semester_id' => 1,
            ),
            42 => 
            array (
                'id' => 98,
                'amount' => '9000.00',
                'release_type' => 'Full',
                'dv_no' => NULL,
                'month' => '2023-06-07',
                'attachment' => '[{"file": "reimbursements/reimbursement_23-06-07085416.pdf", "name": "reimbursement_23-06-07085416.pdf", "added_by": 1, "created_at": "Jun 07, 2023 8:54 am"}]',
                'is_reimbursed' => 1,
                'status_id' => 12,
                'benefit_id' => 6,
                'scholar_id' => 924,
                'release_id' => 1,
                'school_semester_id' => 1,
            ),
            43 => 
            array (
                'id' => 99,
                'amount' => '9000.00',
                'release_type' => 'Full',
                'dv_no' => NULL,
                'month' => '2023-06-07',
                'attachment' => '[{"file": "reimbursements/reimbursement_23-06-07085446.pdf", "name": "reimbursement_23-06-07085446.pdf", "added_by": 1, "created_at": "Jun 07, 2023 8:54 am"}]',
                'is_reimbursed' => 1,
                'status_id' => 12,
                'benefit_id' => 6,
                'scholar_id' => 925,
                'release_id' => 1,
                'school_semester_id' => 1,
            ),
            44 => 
            array (
                'id' => 100,
                'amount' => '9000.00',
                'release_type' => 'Full',
                'dv_no' => NULL,
                'month' => '2023-06-07',
                'attachment' => '[{"file": "reimbursements/reimbursement_23-06-07085512.pdf", "name": "reimbursement_23-06-07085512.pdf", "added_by": 1, "created_at": "Jun 07, 2023 8:55 am"}]',
                'is_reimbursed' => 1,
                'status_id' => 12,
                'benefit_id' => 6,
                'scholar_id' => 1022,
                'release_id' => 1,
                'school_semester_id' => 1,
            ),
            45 => 
            array (
                'id' => 101,
                'amount' => '9000.00',
                'release_type' => 'Full',
                'dv_no' => NULL,
                'month' => '2023-06-07',
                'attachment' => '[{"file": "reimbursements/reimbursement_23-06-07085636.pdf", "name": "reimbursement_23-06-07085636.pdf", "added_by": 1, "created_at": "Jun 07, 2023 8:56 am"}]',
                'is_reimbursed' => 1,
                'status_id' => 12,
                'benefit_id' => 6,
                'scholar_id' => 927,
                'release_id' => 1,
                'school_semester_id' => 1,
            ),
            46 => 
            array (
                'id' => 102,
                'amount' => '9000.00',
                'release_type' => 'Full',
                'dv_no' => NULL,
                'month' => '2023-06-07',
                'attachment' => '[{"file": "reimbursements/reimbursement_23-06-07085743.pdf", "name": "reimbursement_23-06-07085743.pdf", "added_by": 1, "created_at": "Jun 07, 2023 8:57 am"}]',
                'is_reimbursed' => 1,
                'status_id' => 12,
                'benefit_id' => 6,
                'scholar_id' => 935,
                'release_id' => 1,
                'school_semester_id' => 1,
            ),
            47 => 
            array (
                'id' => 103,
                'amount' => '1000.00',
                'release_type' => 'Full',
                'dv_no' => NULL,
                'month' => '2023-06-07',
                'attachment' => '[{"file": "reimbursements/reimbursement_23-06-07085842.pdf", "name": "reimbursement_23-06-07085842.pdf", "added_by": 1, "created_at": "Jun 07, 2023 8:58 am"}]',
                'is_reimbursed' => 1,
                'status_id' => 12,
                'benefit_id' => 6,
                'scholar_id' => 945,
                'release_id' => 1,
                'school_semester_id' => 1,
            ),
            48 => 
            array (
                'id' => 104,
                'amount' => '9000.00',
                'release_type' => 'Full',
                'dv_no' => NULL,
                'month' => '2023-06-07',
                'attachment' => '[{"file": "reimbursements/reimbursement_23-06-07085906.pdf", "name": "reimbursement_23-06-07085906.pdf", "added_by": 1, "created_at": "Jun 07, 2023 8:59 am"}]',
                'is_reimbursed' => 1,
                'status_id' => 12,
                'benefit_id' => 6,
                'scholar_id' => 946,
                'release_id' => 1,
                'school_semester_id' => 1,
            ),
            49 => 
            array (
                'id' => 105,
                'amount' => '1000.00',
                'release_type' => 'Full',
                'dv_no' => NULL,
                'month' => '2023-06-07',
                'attachment' => '[{"file": "reimbursements/reimbursement_23-06-07090018.pdf", "name": "reimbursement_23-06-07090018.pdf", "added_by": 1, "created_at": "Jun 07, 2023 9:00 am"}]',
                'is_reimbursed' => 1,
                'status_id' => 12,
                'benefit_id' => 6,
                'scholar_id' => 948,
                'release_id' => 1,
                'school_semester_id' => 1,
            ),
            50 => 
            array (
                'id' => 106,
                'amount' => '1000.00',
                'release_type' => 'Full',
                'dv_no' => NULL,
                'month' => '2023-06-07',
                'attachment' => '[{"file": "reimbursements/reimbursement_23-06-07090215.pdf", "name": "reimbursement_23-06-07090215.pdf", "added_by": 1, "created_at": "Jun 07, 2023 9:02 am"}]',
                'is_reimbursed' => 1,
                'status_id' => 12,
                'benefit_id' => 6,
                'scholar_id' => 952,
                'release_id' => 1,
                'school_semester_id' => 1,
            ),
        ));
        
        
    }
}